// Generated by scripts/build-wasm.mjs from Rust presets. Do not edit.
export interface Family {
  age: number;
  canopy: {
  clump: number;
  clumpSpan: number;
  divergence: number;
  forwardLean: number;
  leanRise: number;
  maxInstances: number;
  outward: number;
  scatter: number;
  shootRadius: number;
  size: number;
  sizeVariation: number;
  spacing: number;
  surfaceContact: number;
  upward: number;
};
  element: {
  axialSegments: number;
  baseFullness: number;
  card: boolean;
  connectorLength: number;
  crossSegments: number;
  cup: number;
  curl: number;
  length: number;
  lobeCount: number;
  lobeDepth: number;
  sectionRoundness: number;
  tipSharpness: number;
  widestAt: number;
  width: number;
};
  growth: {
  apicalControlLoss: number;
  leafLifetime: number;
  rate: number;
  resizeTolerance: number;
  shape: number;
  sheddingTolerance: number;
};
  material: {
  barkBlue: number;
  barkGreen: number;
  barkMottleScale: number;
  barkMottleStrength: number;
  barkRed: number;
  barkRoughness: number;
  bladeMottleScale: number;
  bladeMottleStrength: number;
  brightnessRangeHigh: number;
  brightnessRangeLow: number;
  cavityStrength: number;
  crestBlue: number;
  crestGreen: number;
  crestRed: number;
  crestStrength: number;
  cuticleGloss: number;
  fissureBlue: number;
  fissureGreen: number;
  fissureRed: number;
  fissureStrength: number;
  furrowStrength: number;
  hueRangeHigh: number;
  hueRangeLow: number;
  interiorDarkening: number;
  leafBackBlue: number;
  leafBackGreen: number;
  leafBackRed: number;
  leafFrontBlue: number;
  leafFrontGreen: number;
  leafFrontRed: number;
  marginBlue: number;
  marginGreen: number;
  marginRed: number;
  marginWidth: number;
  plateScale: number;
  ridgeScale: number;
  roughnessDetail: number;
  skyOcclusionStrength: number;
  thickness: number;
  transmissionBlue: number;
  transmissionGreen: number;
  transmissionRed: number;
  transmissionStrength: number;
  veinContrast: number;
  veinScale: number;
};
  radii: {
  forkExponent: number;
  lengthTaper: number;
  trunkRadius: number;
};
  shellDepth: number;
  skeleton: {
  attractors: number;
  bias: {
  gravitropism: number;
  lean: number;
  supernatural: {
  enabled: boolean;
  spiralRate: number;
  writheAmplitude: number;
  writheWavelength: number;
};
};
  envelope: {
  crownBase: number;
  fullness: number;
  height: number;
  irregularity: number;
  lobeScale: number;
  shoulder: number;
  spread: number;
};
  growth: {
  influenceRadius?: number;
  killDistance?: number;
  maxNodes?: number;
  maxTurnPerStep: number;
  stepDistance?: number;
  trunkHeight?: number;
};
  habit: {
  apicalDominance: number;
  attractorWeight: number;
  crookedness: number;
  lateralLengthRatio: number;
  lateralOrders: number;
  lateralPitch: number;
  lateralSpacing: number;
  lateralsPerStation: number;
  leaderInternode: number;
  pitchVariation: number;
  risePrimary: number;
  riseSecondary: number;
  sheddingThreshold: number;
  twigTipTaper: number;
  whorlStrength: number;
};
  seed: number;
  step: number;
  twigs: {
  angle: number;
  angleVariation: number;
  curtainSeparation: number;
  divergence: number;
  hang: number;
  internodeFactor: number;
  laterals: number;
  lengthRatio: number;
  limbRadius: number;
  pendulousLength: number;
  pendulousRadius: number;
  ratioPower: number;
  reach: number;
  twig: {
  bearingDiameter: number;
  diameter: number;
  internodeLength: number;
  length: number;
  stationsPerInternode: number;
};
  vigourVariation: number;
};
};
  surface: {
  flareDepth: number;
  flareFalloff: number;
  flareRadius: number;
  forkSocket: number;
  forkSwell: number;
  lobeDepth: number;
  lobes: number;
  radialSegments: number;
  twistRate: number;
};
}
export const CATALOGUE: { abiId: number; id: string; name: string; note: string; family: Family }[] = [
  {
    "abiId": 0,
    "family": {
      "age": 100,
      "canopy": {
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 137.508,
        "forwardLean": 0,
        "leanRise": 0,
        "maxInstances": 4294967295,
        "outward": 0.6,
        "scatter": 18,
        "shootRadius": 0,
        "size": 1,
        "sizeVariation": 0.35,
        "spacing": 0.006,
        "surfaceContact": 0,
        "upward": 0.35
      },
      "element": {
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.01,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.12,
        "lobeCount": 0,
        "lobeDepth": 0,
        "sectionRoundness": 0,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.06
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 1,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.068,
        "barkGreen": 0.105,
        "barkMottleScale": 0,
        "barkMottleStrength": 0,
        "barkRed": 0.147,
        "barkRoughness": 0.8,
        "bladeMottleScale": 0,
        "bladeMottleStrength": 0,
        "brightnessRangeHigh": 0.12,
        "brightnessRangeLow": -0.12,
        "cavityStrength": 0,
        "crestBlue": 0,
        "crestGreen": 0,
        "crestRed": 0,
        "crestStrength": 0,
        "cuticleGloss": 0,
        "fissureBlue": 0,
        "fissureGreen": 0,
        "fissureRed": 0,
        "fissureStrength": 0,
        "furrowStrength": 1,
        "hueRangeHigh": 0.03,
        "hueRangeLow": -0.03,
        "interiorDarkening": 0.5,
        "leafBackBlue": 0.07,
        "leafBackGreen": 0.24,
        "leafBackRed": 0.105,
        "leafFrontBlue": 0.036,
        "leafFrontGreen": 0.195,
        "leafFrontRed": 0.068,
        "marginBlue": 0,
        "marginGreen": 0,
        "marginRed": 0,
        "marginWidth": 0,
        "plateScale": 0,
        "ridgeScale": 0,
        "roughnessDetail": 0,
        "skyOcclusionStrength": 0,
        "thickness": 1,
        "transmissionBlue": 0.1,
        "transmissionGreen": 0.6,
        "transmissionRed": 0.3,
        "transmissionStrength": 0,
        "veinContrast": 0,
        "veinScale": 8
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.02
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0.7,
          "lean": 0.05,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.3,
          "fullness": 0.45,
          "height": 24,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 2.2,
          "spread": 0.3
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "apicalDominance": 0.5,
          "attractorWeight": 1,
          "crookedness": 12,
          "lateralLengthRatio": 0.4,
          "lateralOrders": 3,
          "lateralPitch": 60,
          "lateralSpacing": 0.9,
          "lateralsPerStation": 3,
          "leaderInternode": 1.5,
          "pitchVariation": 15,
          "risePrimary": 0.05,
          "riseSecondary": 0,
          "sheddingThreshold": 0.45,
          "twigTipTaper": 1,
          "whorlStrength": 0.3
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 4,
          "divergence": 137.508,
          "hang": 0,
          "internodeFactor": 2.5,
          "laterals": 2,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "pendulousLength": 0.25,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.05,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "ordinary",
    "name": "Ordinary",
    "note": "Natural baseline"
  },
  {
    "abiId": 3,
    "family": {
      "age": 100,
      "canopy": {
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 180,
        "forwardLean": 0.25,
        "leanRise": 0,
        "maxInstances": 4294967295,
        "outward": 0,
        "scatter": 18,
        "shootRadius": 0,
        "size": 1,
        "sizeVariation": 0.2,
        "spacing": 0.006,
        "surfaceContact": 0,
        "upward": 0
      },
      "element": {
        "axialSegments": 40,
        "baseFullness": 0.6,
        "card": false,
        "connectorLength": 0.012,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.1,
        "lobeCount": 5,
        "lobeDepth": 0.7,
        "sectionRoundness": 0,
        "tipSharpness": 0.6,
        "widestAt": 0.55,
        "width": 0.075
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 1,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.198,
        "barkGreen": 0.218,
        "barkMottleScale": 0.8,
        "barkMottleStrength": 0.2,
        "barkRed": 0.225,
        "barkRoughness": 0.85,
        "bladeMottleScale": 6,
        "bladeMottleStrength": 0.15,
        "brightnessRangeHigh": 0.15,
        "brightnessRangeLow": -0.15,
        "cavityStrength": 0.6,
        "crestBlue": 0.055,
        "crestGreen": 0.085,
        "crestRed": 0.1,
        "crestStrength": 0.5,
        "cuticleGloss": 0.35,
        "fissureBlue": 0.005,
        "fissureGreen": -0.05,
        "fissureRed": -0.1,
        "fissureStrength": 0.65,
        "furrowStrength": 1,
        "hueRangeHigh": 0.03,
        "hueRangeLow": -0.03,
        "interiorDarkening": 0.55,
        "leafBackBlue": 0.112,
        "leafBackGreen": 0.254,
        "leafBackRed": 0.153,
        "leafFrontBlue": 0.016,
        "leafFrontGreen": 0.102,
        "leafFrontRed": 0.028,
        "marginBlue": 0.006,
        "marginGreen": 0.035,
        "marginRed": 0.025,
        "marginWidth": 0.08,
        "plateScale": 0.055,
        "ridgeScale": 0.032,
        "roughnessDetail": 0.12,
        "skyOcclusionStrength": 0.5,
        "thickness": 0.65,
        "transmissionBlue": 0.07,
        "transmissionGreen": 0.52,
        "transmissionRed": 0.24,
        "transmissionStrength": 0.55,
        "veinContrast": 0.45,
        "veinScale": 7
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.018
      },
      "shellDepth": 1,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0,
          "lean": 0,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.16,
          "fullness": 0.55,
          "height": 24,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 2.2,
          "spread": 0.55
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "apicalDominance": 0.1,
          "attractorWeight": 0,
          "crookedness": 24,
          "lateralLengthRatio": 0.45,
          "lateralOrders": 3,
          "lateralPitch": 55,
          "lateralSpacing": 1.6,
          "lateralsPerStation": 5,
          "leaderInternode": 2,
          "pitchVariation": 20,
          "risePrimary": 0.12,
          "riseSecondary": 0,
          "sheddingThreshold": 0,
          "twigTipTaper": 0.25,
          "whorlStrength": 0.1
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 4,
          "divergence": 137.508,
          "hang": 0,
          "internodeFactor": 2.5,
          "laterals": 4,
          "lengthRatio": 0.45,
          "limbRadius": 0.1,
          "pendulousLength": 0.25,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.03,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "oregon-white-oak",
    "name": "Oregon white oak",
    "note": "Quercus garryana"
  },
  {
    "abiId": 4,
    "family": {
      "age": 100,
      "canopy": {
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 137.508,
        "forwardLean": 0.05,
        "leanRise": 1.2,
        "maxInstances": 4294967295,
        "outward": 0,
        "scatter": 18,
        "shootRadius": 0.025,
        "size": 1,
        "sizeVariation": 0.2,
        "spacing": 0.006,
        "surfaceContact": 1,
        "upward": 0
      },
      "element": {
        "axialSegments": 5,
        "baseFullness": 0.2,
        "card": false,
        "connectorLength": 0.001,
        "crossSegments": 4,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.018,
        "lobeCount": 0,
        "lobeDepth": 0,
        "sectionRoundness": 1,
        "tipSharpness": 0.2,
        "widestAt": 0.2,
        "width": 0.0015
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 6,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.045,
        "barkGreen": 0.078,
        "barkMottleScale": 0.4,
        "barkMottleStrength": 0.2,
        "barkRed": 0.147,
        "barkRoughness": 0.9,
        "bladeMottleScale": 8,
        "bladeMottleStrength": 0,
        "brightnessRangeHigh": 0.1,
        "brightnessRangeLow": -0.1,
        "cavityStrength": 0.6,
        "crestBlue": 0.01,
        "crestGreen": 0.025,
        "crestRed": 0.05,
        "crestStrength": 0.3,
        "cuticleGloss": 0.05,
        "fissureBlue": -0.02,
        "fissureGreen": -0.03,
        "fissureRed": -0.035,
        "fissureStrength": 0.4,
        "furrowStrength": 0.025,
        "hueRangeHigh": 0.02,
        "hueRangeLow": -0.02,
        "interiorDarkening": 0.7,
        "leafBackBlue": 0.138,
        "leafBackGreen": 0.195,
        "leafBackRed": 0.109,
        "leafFrontBlue": 0.028,
        "leafFrontGreen": 0.056,
        "leafFrontRed": 0.018,
        "marginBlue": 0.002,
        "marginGreen": 0.015,
        "marginRed": 0.01,
        "marginWidth": 0,
        "plateScale": 0.03,
        "ridgeScale": 0.02,
        "roughnessDetail": 0.16,
        "skyOcclusionStrength": 0.6,
        "thickness": 3.5,
        "transmissionBlue": 0.08,
        "transmissionGreen": 0.24,
        "transmissionRed": 0.12,
        "transmissionStrength": 0.01,
        "veinContrast": 0,
        "veinScale": 8
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.015
      },
      "shellDepth": 1,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0,
          "lean": 0,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.04,
          "fullness": 0.15,
          "height": 15,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 1,
          "spread": 0.31
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "apicalDominance": 1,
          "attractorWeight": 0,
          "crookedness": 0,
          "lateralLengthRatio": 0.3,
          "lateralOrders": 4,
          "lateralPitch": 88,
          "lateralSpacing": 0.15,
          "lateralsPerStation": 5,
          "leaderInternode": 0.9,
          "pitchVariation": 4,
          "risePrimary": 0.12,
          "riseSecondary": -0.8,
          "sheddingThreshold": 0,
          "twigTipTaper": 0.25,
          "whorlStrength": 1
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 4,
          "divergence": 137.508,
          "hang": 1,
          "internodeFactor": 2.5,
          "laterals": 2,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "pendulousLength": 0.25,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.02,
            "diameter": 0.002,
            "internodeLength": 0.0025,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "norway-spruce",
    "name": "Norway spruce",
    "note": "Picea abies"
  },
  {
    "abiId": 5,
    "family": {
      "age": 120,
      "canopy": {
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 180,
        "forwardLean": 0.2,
        "leanRise": 0,
        "maxInstances": 4294967295,
        "outward": 0,
        "scatter": 18,
        "shootRadius": 0,
        "size": 1,
        "sizeVariation": 0.2,
        "spacing": 0.006,
        "surfaceContact": 0,
        "upward": 0
      },
      "element": {
        "axialSegments": 8,
        "baseFullness": 0.75,
        "card": false,
        "connectorLength": 0.008,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.08,
        "lobeCount": 0,
        "lobeDepth": 0,
        "sectionRoundness": 0,
        "tipSharpness": 0.7,
        "widestAt": 0.45,
        "width": 0.05
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 1,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.295,
        "barkGreen": 0.335,
        "barkMottleScale": 0.6,
        "barkMottleStrength": 0.12,
        "barkRed": 0.36,
        "barkRoughness": 0.4,
        "bladeMottleScale": 5,
        "bladeMottleStrength": 0.1,
        "brightnessRangeHigh": 0.1,
        "brightnessRangeLow": -0.1,
        "cavityStrength": 0.35,
        "crestBlue": 0.045,
        "crestGreen": 0.055,
        "crestRed": 0.06,
        "crestStrength": 0.25,
        "cuticleGloss": 0.48,
        "fissureBlue": -0.02,
        "fissureGreen": -0.03,
        "fissureRed": -0.04,
        "fissureStrength": 0.2,
        "furrowStrength": 0.12,
        "hueRangeHigh": 0.02,
        "hueRangeLow": -0.02,
        "interiorDarkening": 0.35,
        "leafBackBlue": 0.1,
        "leafBackGreen": 0.23,
        "leafBackRed": 0.14,
        "leafFrontBlue": 0.018,
        "leafFrontGreen": 0.105,
        "leafFrontRed": 0.022,
        "marginBlue": 0.008,
        "marginGreen": 0.04,
        "marginRed": 0.02,
        "marginWidth": 0.04,
        "plateScale": 0.04,
        "ridgeScale": 0.018,
        "roughnessDetail": 0.08,
        "skyOcclusionStrength": 0.35,
        "thickness": 0.6,
        "transmissionBlue": 0.08,
        "transmissionGreen": 0.5,
        "transmissionRed": 0.22,
        "transmissionStrength": 0.5,
        "veinContrast": 0.4,
        "veinScale": 7
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.014
      },
      "shellDepth": 1,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0,
          "lean": 0,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.12,
          "fullness": 0.62,
          "height": 32,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 1.8,
          "spread": 0.52
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "apicalDominance": 0.2,
          "attractorWeight": 0,
          "crookedness": 14,
          "lateralLengthRatio": 0.46,
          "lateralOrders": 3,
          "lateralPitch": 50,
          "lateralSpacing": 1.4,
          "lateralsPerStation": 4,
          "leaderInternode": 2.2,
          "pitchVariation": 12,
          "risePrimary": 0.08,
          "riseSecondary": 0,
          "sheddingThreshold": 0,
          "twigTipTaper": 0.25,
          "whorlStrength": 0.15
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 4,
          "divergence": 137.508,
          "hang": 0,
          "internodeFactor": 2.5,
          "laterals": 5,
          "lengthRatio": 0.42,
          "limbRadius": 0.1,
          "pendulousLength": 0.25,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.03,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 1.5,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "european-beech",
    "name": "European beech",
    "note": "Fagus sylvatica"
  },
  {
    "abiId": 6,
    "family": {
      "age": 70,
      "canopy": {
        "clump": 8,
        "clumpSpan": 0.5,
        "divergence": 180,
        "forwardLean": 0.6,
        "leanRise": 0.3,
        "maxInstances": 4294967295,
        "outward": 0,
        "scatter": 18,
        "shootRadius": 0,
        "size": 1,
        "sizeVariation": 0.2,
        "spacing": 0.006,
        "surfaceContact": 0,
        "upward": -0.35
      },
      "element": {
        "axialSegments": 8,
        "baseFullness": 0.55,
        "card": false,
        "connectorLength": 0.022,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.055,
        "lobeCount": 0,
        "lobeDepth": 0,
        "sectionRoundness": 0,
        "tipSharpness": 1.8,
        "widestAt": 0.28,
        "width": 0.045
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 1,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.7,
        "barkGreen": 0.76,
        "barkMottleScale": 0.9,
        "barkMottleStrength": 0.18,
        "barkRed": 0.78,
        "barkRoughness": 0.48,
        "bladeMottleScale": 5.5,
        "bladeMottleStrength": 0.12,
        "brightnessRangeHigh": 0.12,
        "brightnessRangeLow": -0.12,
        "cavityStrength": 0.3,
        "crestBlue": 0.06,
        "crestGreen": 0.07,
        "crestRed": 0.08,
        "crestStrength": 0.2,
        "cuticleGloss": 0.28,
        "fissureBlue": -0.22,
        "fissureGreen": -0.24,
        "fissureRed": -0.25,
        "fissureStrength": 0.45,
        "furrowStrength": 0.25,
        "hueRangeHigh": 0.025,
        "hueRangeLow": -0.025,
        "interiorDarkening": 0.4,
        "leafBackBlue": 0.11,
        "leafBackGreen": 0.27,
        "leafBackRed": 0.18,
        "leafFrontBlue": 0.035,
        "leafFrontGreen": 0.165,
        "leafFrontRed": 0.055,
        "marginBlue": 0.01,
        "marginGreen": 0.05,
        "marginRed": 0.03,
        "marginWidth": 0.05,
        "plateScale": 0.05,
        "ridgeScale": 0.025,
        "roughnessDetail": 0.1,
        "skyOcclusionStrength": 0.4,
        "thickness": 0.45,
        "transmissionBlue": 0.1,
        "transmissionGreen": 0.55,
        "transmissionRed": 0.28,
        "transmissionStrength": 0.6,
        "veinContrast": 0.35,
        "veinScale": 6
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.01
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0,
          "lean": 0,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.015,
          "fullness": 0.6,
          "height": 18,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 1.6,
          "spread": 0.36
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "apicalDominance": 0.45,
          "attractorWeight": 0,
          "crookedness": 10,
          "lateralLengthRatio": 0.4,
          "lateralOrders": 3,
          "lateralPitch": 62,
          "lateralSpacing": 1.2,
          "lateralsPerStation": 4,
          "leaderInternode": 1.6,
          "pitchVariation": 14,
          "risePrimary": 0.02,
          "riseSecondary": -0.85,
          "sheddingThreshold": 0,
          "twigTipTaper": 0.35,
          "whorlStrength": 0.2
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 9,
          "divergence": 137.508,
          "hang": 2.4,
          "internodeFactor": 2.5,
          "laterals": 8,
          "lengthRatio": 0.6,
          "limbRadius": 0.1,
          "pendulousLength": 3.5,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.02,
            "diameter": 0.003,
            "internodeLength": 0.012,
            "length": 0.45,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "silver-birch",
    "name": "Silver birch",
    "note": "Betula pendula"
  },
  {
    "abiId": 1,
    "family": {
      "age": 100,
      "canopy": {
        "clump": 6,
        "clumpSpan": 0.28,
        "divergence": 137.508,
        "forwardLean": 0,
        "leanRise": 0,
        "maxInstances": 4294967295,
        "outward": 0.42,
        "scatter": 14,
        "shootRadius": 0,
        "size": 1,
        "sizeVariation": 0.28,
        "spacing": 0.0045,
        "surfaceContact": 0,
        "upward": 0.55
      },
      "element": {
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.01,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.12,
        "lobeCount": 0,
        "lobeDepth": 0,
        "sectionRoundness": 0,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.06
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 1,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.068,
        "barkGreen": 0.105,
        "barkMottleScale": 0,
        "barkMottleStrength": 0.05,
        "barkRed": 0.147,
        "barkRoughness": 0.8,
        "bladeMottleScale": 0,
        "bladeMottleStrength": 0.04,
        "brightnessRangeHigh": 0.12,
        "brightnessRangeLow": -0.12,
        "cavityStrength": 0.2,
        "crestBlue": 0,
        "crestGreen": 0,
        "crestRed": 0,
        "crestStrength": 0.1,
        "cuticleGloss": 0.25,
        "fissureBlue": 0,
        "fissureGreen": 0,
        "fissureRed": 0,
        "fissureStrength": 0.12,
        "furrowStrength": 1,
        "hueRangeHigh": 0.03,
        "hueRangeLow": -0.03,
        "interiorDarkening": 0.5,
        "leafBackBlue": 0.07,
        "leafBackGreen": 0.24,
        "leafBackRed": 0.105,
        "leafFrontBlue": 0.036,
        "leafFrontGreen": 0.195,
        "leafFrontRed": 0.068,
        "marginBlue": 0,
        "marginGreen": 0,
        "marginRed": 0,
        "marginWidth": 0,
        "plateScale": 0,
        "ridgeScale": 0,
        "roughnessDetail": 0,
        "skyOcclusionStrength": 0.2,
        "thickness": 1,
        "transmissionBlue": 0.1,
        "transmissionGreen": 0.6,
        "transmissionRed": 0.3,
        "transmissionStrength": 0,
        "veinContrast": 0,
        "veinScale": 8
      },
      "radii": {
        "forkExponent": 2.15,
        "lengthTaper": 0.75,
        "trunkRadius": 0.05
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 1600,
        "bias": {
          "gravitropism": 0.95,
          "lean": 0.04,
          "supernatural": {
            "enabled": true,
            "spiralRate": 2.6,
            "writheAmplitude": 0.11,
            "writheWavelength": 0.34
          }
        },
        "envelope": {
          "crownBase": 0.38,
          "fullness": 0.58,
          "height": 148,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 1.5,
          "spread": 0.24
        },
        "growth": {
          "maxTurnPerStep": 26
        },
        "habit": {
          "apicalDominance": 0.15,
          "attractorWeight": 1,
          "crookedness": 12,
          "lateralLengthRatio": 0.45,
          "lateralOrders": 3,
          "lateralPitch": 60,
          "lateralSpacing": 10,
          "lateralsPerStation": 4,
          "leaderInternode": 10,
          "pitchVariation": 15,
          "risePrimary": 0.05,
          "riseSecondary": 0,
          "sheddingThreshold": 0.45,
          "twigTipTaper": 1,
          "whorlStrength": 0.2
        },
        "seed": 1,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 4,
          "divergence": 137.508,
          "hang": 0,
          "internodeFactor": 3.5,
          "laterals": 4,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "pendulousLength": 0.25,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.05,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.5,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0.11,
        "lobes": 7,
        "radialSegments": 12,
        "twistRate": 2.4
      }
    },
    "id": "telperion",
    "name": "Telperion",
    "note": "The silver tree"
  },
  {
    "abiId": 2,
    "family": {
      "age": 100,
      "canopy": {
        "clump": 9,
        "clumpSpan": 0.36,
        "divergence": 99.502,
        "forwardLean": 0,
        "leanRise": 0,
        "maxInstances": 4294967295,
        "outward": 0.72,
        "scatter": 22,
        "shootRadius": 0,
        "size": 1.5,
        "sizeVariation": 0.4,
        "spacing": 0.0065,
        "surfaceContact": 0,
        "upward": 0.22
      },
      "element": {
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.01,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.12,
        "lobeCount": 0,
        "lobeDepth": 0,
        "sectionRoundness": 0,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.06
      },
      "growth": {
        "apicalControlLoss": 0,
        "leafLifetime": 1,
        "rate": 0.08,
        "resizeTolerance": 0.0001,
        "shape": 2,
        "sheddingTolerance": 2
      },
      "material": {
        "barkBlue": 0.068,
        "barkGreen": 0.105,
        "barkMottleScale": 0,
        "barkMottleStrength": 0.05,
        "barkRed": 0.147,
        "barkRoughness": 0.8,
        "bladeMottleScale": 0,
        "bladeMottleStrength": 0.04,
        "brightnessRangeHigh": 0.12,
        "brightnessRangeLow": -0.12,
        "cavityStrength": 0.2,
        "crestBlue": 0,
        "crestGreen": 0,
        "crestRed": 0,
        "crestStrength": 0.1,
        "cuticleGloss": 0.3,
        "fissureBlue": 0,
        "fissureGreen": 0,
        "fissureRed": 0,
        "fissureStrength": 0.12,
        "furrowStrength": 1,
        "hueRangeHigh": 0.03,
        "hueRangeLow": -0.03,
        "interiorDarkening": 0.5,
        "leafBackBlue": 0.07,
        "leafBackGreen": 0.24,
        "leafBackRed": 0.105,
        "leafFrontBlue": 0.036,
        "leafFrontGreen": 0.195,
        "leafFrontRed": 0.068,
        "marginBlue": 0,
        "marginGreen": 0,
        "marginRed": 0,
        "marginWidth": 0,
        "plateScale": 0,
        "ridgeScale": 0,
        "roughnessDetail": 0,
        "skyOcclusionStrength": 0.2,
        "thickness": 1,
        "transmissionBlue": 0.1,
        "transmissionGreen": 0.6,
        "transmissionRed": 0.3,
        "transmissionStrength": 0,
        "veinContrast": 0,
        "veinScale": 8
      },
      "radii": {
        "forkExponent": 2.7,
        "lengthTaper": 0.35,
        "trunkRadius": 0.055
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 1060,
        "bias": {
          "gravitropism": 0.55,
          "lean": 0.06,
          "supernatural": {
            "enabled": true,
            "spiralRate": 0.6,
            "writheAmplitude": 0.05,
            "writheWavelength": 0.8
          }
        },
        "envelope": {
          "crownBase": 0.24,
          "fullness": 0.38,
          "height": 132,
          "irregularity": 0,
          "lobeScale": 0.5,
          "shoulder": 3.2,
          "spread": 0.58
        },
        "growth": {
          "maxTurnPerStep": 46
        },
        "habit": {
          "apicalDominance": 0.15,
          "attractorWeight": 1,
          "crookedness": 12,
          "lateralLengthRatio": 0.45,
          "lateralOrders": 3,
          "lateralPitch": 60,
          "lateralSpacing": 10,
          "lateralsPerStation": 4,
          "leaderInternode": 10,
          "pitchVariation": 15,
          "risePrimary": 0.05,
          "riseSecondary": 0,
          "sheddingThreshold": 0.45,
          "twigTipTaper": 1,
          "whorlStrength": 0.2
        },
        "seed": 2,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "curtainSeparation": 4,
          "divergence": 137.508,
          "hang": 0,
          "internodeFactor": 6,
          "laterals": 2,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "pendulousLength": 0.25,
          "pendulousRadius": 1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.05,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.5,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 3.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0.24,
        "lobes": 4,
        "radialSegments": 12,
        "twistRate": 0.8
      }
    },
    "id": "laurelin",
    "name": "Laurelin",
    "note": "The golden tree"
  }
];
