// Generated by scripts/build-wasm.mjs from Rust presets. Do not edit.
export interface Family {
  canopy: {
  attachment: "generic" | "alternate" | "radialNeedles";
  clump: number;
  clumpSpan: number;
  divergence: number;
  maxInstances: number;
  outward: number;
  scatter: number;
  shootRadius: number;
  size: number;
  sizeVariation: number;
  spacing: number;
  upward: number;
};
  element: {
  anatomy: "genericBlade" | "lobedBlade" | "fourSidedNeedle";
  axialSegments: number;
  baseFullness: number;
  card: boolean;
  connectorLength: number;
  crossSegments: number;
  cup: number;
  curl: number;
  length: number;
  tipSharpness: number;
  widestAt: number;
  width: number;
};
  radii: {
  forkExponent: number;
  lengthTaper: number;
  trunkRadius: number;
};
  shellDepth: number;
  skeleton: {
  attractors: number;
  bias: {
  gravitropism: number;
  lean: number;
  supernatural: {
  enabled: boolean;
  spiralRate: number;
  writheAmplitude: number;
  writheWavelength: number;
};
};
  envelope: {
  crownBase: number;
  fullness: number;
  height: number;
  shoulder: number;
  spread: number;
};
  growth: {
  influenceRadius?: number;
  killDistance?: number;
  maxNodes?: number;
  maxTurnPerStep: number;
  stepDistance?: number;
  trunkHeight?: number;
};
  habit: {
  kind: "colonizing";
} | {
  crookedness: number;
  kind: "spreading";
  scaffoldLimbs: number;
  subdivisions: number;
} | {
  branchesPerTier: number;
  kind: "tiered";
  secondaryLength: number;
  secondarySpacing: number;
  tiers: number;
  upturn: number;
};
  seed: number;
  step: number;
  twigs: {
  angle: number;
  angleVariation: number;
  divergence: number;
  internodeFactor: number;
  laterals: number;
  lengthRatio: number;
  limbRadius: number;
  ratioPower: number;
  reach: number;
  twig: {
  bearingDiameter: number;
  diameter: number;
  internodeLength: number;
  length: number;
  stationsPerInternode: number;
};
  vigourVariation: number;
};
};
  surface: {
  flareDepth: number;
  flareFalloff: number;
  flareRadius: number;
  forkSocket: number;
  forkSwell: number;
  lobeDepth: number;
  lobes: number;
  radialSegments: number;
  twistRate: number;
};
}
export const CATALOGUE: { abiId: number; id: string; name: string; note: string; family: Family }[] = [
  {
    "abiId": 0,
    "family": {
      "canopy": {
        "attachment": "generic",
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 137.508,
        "maxInstances": 4294967295,
        "outward": 0.6,
        "scatter": 18,
        "shootRadius": 0.12,
        "size": 1,
        "sizeVariation": 0.35,
        "spacing": 0.006,
        "upward": 0.35
      },
      "element": {
        "anatomy": "genericBlade",
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.01,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.12,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.06
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.02
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0.7,
          "lean": 0.05,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.3,
          "fullness": 0.45,
          "height": 24,
          "shoulder": 2.2,
          "spread": 0.3
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "kind": "colonizing"
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "divergence": 137.508,
          "internodeFactor": 2.5,
          "laterals": 2,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.05,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "ordinary",
    "name": "Ordinary",
    "note": "Natural baseline"
  },
  {
    "abiId": 3,
    "family": {
      "canopy": {
        "attachment": "alternate",
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 180,
        "maxInstances": 4294967295,
        "outward": 0.6,
        "scatter": 18,
        "shootRadius": 0.12,
        "size": 1,
        "sizeVariation": 0.2,
        "spacing": 0.006,
        "upward": 0.35
      },
      "element": {
        "anatomy": "lobedBlade",
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.012,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.1,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.075
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.018
      },
      "shellDepth": 1,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0,
          "lean": 0,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.16,
          "fullness": 0.55,
          "height": 24,
          "shoulder": 2.2,
          "spread": 0.55
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "crookedness": 24,
          "kind": "spreading",
          "scaffoldLimbs": 5,
          "subdivisions": 5
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "divergence": 137.508,
          "internodeFactor": 2.5,
          "laterals": 4,
          "lengthRatio": 0.45,
          "limbRadius": 0.1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.03,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "oregon-white-oak",
    "name": "Oregon white oak",
    "note": "Quercus garryana"
  },
  {
    "abiId": 4,
    "family": {
      "canopy": {
        "attachment": "radialNeedles",
        "clump": 5,
        "clumpSpan": 0.3,
        "divergence": 137.508,
        "maxInstances": 4294967295,
        "outward": 0.6,
        "scatter": 18,
        "shootRadius": 0.025,
        "size": 1,
        "sizeVariation": 0.2,
        "spacing": 0.006,
        "upward": 0.35
      },
      "element": {
        "anatomy": "fourSidedNeedle",
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.001,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.018,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.0015
      },
      "radii": {
        "forkExponent": 2,
        "lengthTaper": 0.6,
        "trunkRadius": 0.015
      },
      "shellDepth": 1,
      "skeleton": {
        "attractors": 500,
        "bias": {
          "gravitropism": 0,
          "lean": 0,
          "supernatural": {
            "enabled": false,
            "spiralRate": 0,
            "writheAmplitude": 0,
            "writheWavelength": 0.45
          }
        },
        "envelope": {
          "crownBase": 0.04,
          "fullness": 0.15,
          "height": 15,
          "shoulder": 1,
          "spread": 0.31
        },
        "growth": {
          "maxTurnPerStep": 35
        },
        "habit": {
          "branchesPerTier": 5,
          "kind": "tiered",
          "secondaryLength": 0.3,
          "secondarySpacing": 0.2,
          "tiers": 16,
          "upturn": 0.12
        },
        "seed": 42,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "divergence": 137.508,
          "internodeFactor": 2.5,
          "laterals": 2,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.02,
            "diameter": 0.002,
            "internodeLength": 0.0025,
            "length": 0.25,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0,
        "lobes": 5,
        "radialSegments": 12,
        "twistRate": 0
      }
    },
    "id": "norway-spruce",
    "name": "Norway spruce",
    "note": "Picea abies"
  },
  {
    "abiId": 1,
    "family": {
      "canopy": {
        "attachment": "generic",
        "clump": 6,
        "clumpSpan": 0.28,
        "divergence": 137.508,
        "maxInstances": 4294967295,
        "outward": 0.42,
        "scatter": 14,
        "shootRadius": 0.1,
        "size": 1,
        "sizeVariation": 0.28,
        "spacing": 0.0045,
        "upward": 0.55
      },
      "element": {
        "anatomy": "genericBlade",
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.01,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.12,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.06
      },
      "radii": {
        "forkExponent": 2.15,
        "lengthTaper": 0.75,
        "trunkRadius": 0.05
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 1600,
        "bias": {
          "gravitropism": 0.95,
          "lean": 0.04,
          "supernatural": {
            "enabled": true,
            "spiralRate": 2.6,
            "writheAmplitude": 0.11,
            "writheWavelength": 0.34
          }
        },
        "envelope": {
          "crownBase": 0.38,
          "fullness": 0.58,
          "height": 148,
          "shoulder": 1.5,
          "spread": 0.24
        },
        "growth": {
          "maxTurnPerStep": 26
        },
        "habit": {
          "kind": "colonizing"
        },
        "seed": 1,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "divergence": 137.508,
          "internodeFactor": 3.5,
          "laterals": 4,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.05,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.5,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 2,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0.11,
        "lobes": 7,
        "radialSegments": 12,
        "twistRate": 2.4
      }
    },
    "id": "telperion",
    "name": "Telperion",
    "note": "The silver tree"
  },
  {
    "abiId": 2,
    "family": {
      "canopy": {
        "attachment": "generic",
        "clump": 9,
        "clumpSpan": 0.36,
        "divergence": 99.502,
        "maxInstances": 4294967295,
        "outward": 0.72,
        "scatter": 22,
        "shootRadius": 0.14,
        "size": 1.5,
        "sizeVariation": 0.4,
        "spacing": 0.0065,
        "upward": 0.22
      },
      "element": {
        "anatomy": "genericBlade",
        "axialSegments": 5,
        "baseFullness": 0.85,
        "card": false,
        "connectorLength": 0.01,
        "crossSegments": 2,
        "cup": 0.18,
        "curl": 0.12,
        "length": 0.12,
        "tipSharpness": 1.6,
        "widestAt": 0.42,
        "width": 0.06
      },
      "radii": {
        "forkExponent": 2.7,
        "lengthTaper": 0.35,
        "trunkRadius": 0.055
      },
      "shellDepth": 0.45,
      "skeleton": {
        "attractors": 1060,
        "bias": {
          "gravitropism": 0.55,
          "lean": 0.06,
          "supernatural": {
            "enabled": true,
            "spiralRate": 0.6,
            "writheAmplitude": 0.05,
            "writheWavelength": 0.8
          }
        },
        "envelope": {
          "crownBase": 0.24,
          "fullness": 0.38,
          "height": 132,
          "shoulder": 3.2,
          "spread": 0.58
        },
        "growth": {
          "maxTurnPerStep": 46
        },
        "habit": {
          "kind": "colonizing"
        },
        "seed": 2,
        "step": 0.022,
        "twigs": {
          "angle": 45,
          "angleVariation": 10,
          "divergence": 137.508,
          "internodeFactor": 6,
          "laterals": 2,
          "lengthRatio": 0.4,
          "limbRadius": 0.1,
          "ratioPower": 1.3,
          "reach": 0.2,
          "twig": {
            "bearingDiameter": 0.05,
            "diameter": 0.005,
            "internodeLength": 0.02,
            "length": 0.5,
            "stationsPerInternode": 1
          },
          "vigourVariation": 0.15
        }
      },
      "surface": {
        "flareDepth": 0.004,
        "flareFalloff": 0.022,
        "flareRadius": 3.1,
        "forkSocket": 0.5,
        "forkSwell": 1.35,
        "lobeDepth": 0.24,
        "lobes": 4,
        "radialSegments": 12,
        "twistRate": 0.8
      }
    },
    "id": "laurelin",
    "name": "Laurelin",
    "note": "The golden tree"
  }
];
