// Generated by scripts/build-wasm.mjs from Rust presets. Do not edit.
export interface Family {
  canopy: {
  clump: number;
  clumpSpan: number;
  divergence: number;
  maxInstances: number;
  outward: number;
  scatter: number;
  shootRadius: number;
  size: number;
  sizeVariation: number;
  spacing: number;
  upward: number;
};
  element: {
  axialSegments: number;
  baseFullness: number;
  card: boolean;
  crossSegments: number;
  cup: number;
  curl: number;
  length: number;
  tipSharpness: number;
  widestAt: number;
  width: number;
};
  radii: {
  forkExponent: number;
  lengthTaper: number;
  trunkRadius: number;
};
  shellDepth: number;
  skeleton: {
  attractors: number;
  bias: {
  gravitropism: number;
  lean: number;
  spiralRate: number;
  writheAmplitude: number;
  writheWavelength: number;
};
  envelope: {
  crownBase: number;
  fullness: number;
  height: number;
  shoulder: number;
  spread: number;
};
  growth: {
  influenceRadius?: number;
  killDistance?: number;
  maxNodes?: number;
  maxTurnPerStep: number;
  stepDistance?: number;
  trunkHeight?: number;
};
  seed: number;
  step: number;
  twigs: {
  angle: number;
  angleVariation: number;
  divergence: number;
  internodeFactor: number;
  laterals: number;
  lengthRatio: number;
  limbRadius: number;
  ratioPower: number;
  reach: number;
  twig: {
  bearingDiameter: number;
  diameter: number;
  internodeLength: number;
  length: number;
  stationsPerInternode: number;
};
  vigourVariation: number;
};
};
  surface: {
  flareDepth: number;
  flareFalloff: number;
  flareRadius: number;
  forkSocket: number;
  forkSwell: number;
  lobeDepth: number;
  lobes: number;
  radialSegments: number;
  twistRate: number;
};
}
export const FAMILIES: Family[] = [
  {
    "canopy": {
      "clump": 5,
      "clumpSpan": 0.3,
      "divergence": 137.508,
      "maxInstances": 4294967295,
      "outward": 0.6,
      "scatter": 18,
      "shootRadius": 0.12,
      "size": 1,
      "sizeVariation": 0.35,
      "spacing": 0.006,
      "upward": 0.35
    },
    "element": {
      "axialSegments": 5,
      "baseFullness": 0.85,
      "card": false,
      "crossSegments": 2,
      "cup": 0.18,
      "curl": 0.12,
      "length": 0.12,
      "tipSharpness": 1.6,
      "widestAt": 0.42,
      "width": 0.06
    },
    "radii": {
      "forkExponent": 2,
      "lengthTaper": 0.6,
      "trunkRadius": 0.02
    },
    "shellDepth": 0.45,
    "skeleton": {
      "attractors": 500,
      "bias": {
        "gravitropism": 0.7,
        "lean": 0.05,
        "spiralRate": 1.2,
        "writheAmplitude": 0.07,
        "writheWavelength": 0.45
      },
      "envelope": {
        "crownBase": 0.3,
        "fullness": 0.45,
        "height": 24,
        "shoulder": 2.2,
        "spread": 0.3
      },
      "growth": {
        "maxTurnPerStep": 35
      },
      "seed": 42,
      "step": 0.022,
      "twigs": {
        "angle": 45,
        "angleVariation": 10,
        "divergence": 137.508,
        "internodeFactor": 2.5,
        "laterals": 2,
        "lengthRatio": 0.4,
        "limbRadius": 0.1,
        "ratioPower": 1.3,
        "reach": 0.2,
        "twig": {
          "bearingDiameter": 0.05,
          "diameter": 0.005,
          "internodeLength": 0.02,
          "length": 0.25,
          "stationsPerInternode": 1
        },
        "vigourVariation": 0.15
      }
    },
    "surface": {
      "flareDepth": 0.004,
      "flareFalloff": 0.022,
      "flareRadius": 2.1,
      "forkSocket": 0.5,
      "forkSwell": 1.35,
      "lobeDepth": 0.16,
      "lobes": 5,
      "radialSegments": 12,
      "twistRate": 1.5
    }
  },
  {
    "canopy": {
      "clump": 6,
      "clumpSpan": 0.28,
      "divergence": 137.508,
      "maxInstances": 4294967295,
      "outward": 0.42,
      "scatter": 14,
      "shootRadius": 0.1,
      "size": 1,
      "sizeVariation": 0.28,
      "spacing": 0.0045,
      "upward": 0.55
    },
    "element": {
      "axialSegments": 5,
      "baseFullness": 0.85,
      "card": false,
      "crossSegments": 2,
      "cup": 0.18,
      "curl": 0.12,
      "length": 0.12,
      "tipSharpness": 1.6,
      "widestAt": 0.42,
      "width": 0.06
    },
    "radii": {
      "forkExponent": 2.15,
      "lengthTaper": 0.75,
      "trunkRadius": 0.05
    },
    "shellDepth": 0.45,
    "skeleton": {
      "attractors": 1600,
      "bias": {
        "gravitropism": 0.95,
        "lean": 0.04,
        "spiralRate": 2.6,
        "writheAmplitude": 0.11,
        "writheWavelength": 0.34
      },
      "envelope": {
        "crownBase": 0.38,
        "fullness": 0.58,
        "height": 148,
        "shoulder": 1.5,
        "spread": 0.24
      },
      "growth": {
        "maxTurnPerStep": 26
      },
      "seed": 1,
      "step": 0.022,
      "twigs": {
        "angle": 45,
        "angleVariation": 10,
        "divergence": 137.508,
        "internodeFactor": 3.5,
        "laterals": 4,
        "lengthRatio": 0.4,
        "limbRadius": 0.1,
        "ratioPower": 1.3,
        "reach": 0.2,
        "twig": {
          "bearingDiameter": 0.05,
          "diameter": 0.005,
          "internodeLength": 0.02,
          "length": 0.5,
          "stationsPerInternode": 1
        },
        "vigourVariation": 0.15
      }
    },
    "surface": {
      "flareDepth": 0.004,
      "flareFalloff": 0.022,
      "flareRadius": 2,
      "forkSocket": 0.5,
      "forkSwell": 1.35,
      "lobeDepth": 0.11,
      "lobes": 7,
      "radialSegments": 12,
      "twistRate": 2.4
    }
  },
  {
    "canopy": {
      "clump": 9,
      "clumpSpan": 0.36,
      "divergence": 99.502,
      "maxInstances": 4294967295,
      "outward": 0.72,
      "scatter": 22,
      "shootRadius": 0.14,
      "size": 1.5,
      "sizeVariation": 0.4,
      "spacing": 0.0065,
      "upward": 0.22
    },
    "element": {
      "axialSegments": 5,
      "baseFullness": 0.85,
      "card": false,
      "crossSegments": 2,
      "cup": 0.18,
      "curl": 0.12,
      "length": 0.12,
      "tipSharpness": 1.6,
      "widestAt": 0.42,
      "width": 0.06
    },
    "radii": {
      "forkExponent": 2.7,
      "lengthTaper": 0.35,
      "trunkRadius": 0.055
    },
    "shellDepth": 0.45,
    "skeleton": {
      "attractors": 1060,
      "bias": {
        "gravitropism": 0.55,
        "lean": 0.06,
        "spiralRate": 0.6,
        "writheAmplitude": 0.05,
        "writheWavelength": 0.8
      },
      "envelope": {
        "crownBase": 0.24,
        "fullness": 0.38,
        "height": 132,
        "shoulder": 3.2,
        "spread": 0.58
      },
      "growth": {
        "maxTurnPerStep": 46
      },
      "seed": 2,
      "step": 0.022,
      "twigs": {
        "angle": 45,
        "angleVariation": 10,
        "divergence": 137.508,
        "internodeFactor": 6,
        "laterals": 2,
        "lengthRatio": 0.4,
        "limbRadius": 0.1,
        "ratioPower": 1.3,
        "reach": 0.2,
        "twig": {
          "bearingDiameter": 0.05,
          "diameter": 0.005,
          "internodeLength": 0.02,
          "length": 0.5,
          "stationsPerInternode": 1
        },
        "vigourVariation": 0.15
      }
    },
    "surface": {
      "flareDepth": 0.004,
      "flareFalloff": 0.022,
      "flareRadius": 3.1,
      "forkSocket": 0.5,
      "forkSwell": 1.35,
      "lobeDepth": 0.24,
      "lobes": 4,
      "radialSegments": 12,
      "twistRate": 0.8
    }
  }
];
