//! Material value tables kept beside the geometry presets.
use crate::material::MaterialParams;

pub(super) fn oak() -> MaterialParams {
    MaterialParams {
        bark_red: 0.225,
        bark_green: 0.218,
        bark_blue: 0.198,
        bark_roughness: 0.85,
        leaf_front_red: 0.028,
        leaf_front_green: 0.102,
        leaf_front_blue: 0.016,
        leaf_back_red: 0.153,
        leaf_back_green: 0.254,
        leaf_back_blue: 0.112,
        hue_range_low: -0.03,
        hue_range_high: 0.03,
        brightness_range_low: -0.15,
        brightness_range_high: 0.15,
        interior_darkening: 0.55,
        ridge_scale: 0.032,
        plate_scale: 0.055,
        furrow_strength: 1.0,
        roughness_detail: 0.12,
        vein_scale: 7.0,
        vein_contrast: 0.45,
        transmission_strength: 0.55,
        transmission_red: 0.24,
        transmission_green: 0.52,
        transmission_blue: 0.07,
        thickness: 0.65,
        fissure_red: -0.1,
        fissure_green: -0.05,
        fissure_blue: 0.005,
        fissure_strength: 0.65,
        crest_red: 0.1,
        crest_green: 0.085,
        crest_blue: 0.055,
        crest_strength: 0.5,
        bark_mottle_scale: 0.8,
        bark_mottle_strength: 0.2,
        cavity_strength: 0.6,
        blade_mottle_scale: 6.0,
        blade_mottle_strength: 0.15,
        margin_width: 0.08,
        margin_red: 0.025,
        margin_green: 0.035,
        margin_blue: 0.006,
        cuticle_gloss: 0.35,
        sky_occlusion_strength: 0.5,
        plate_cell_scale: 0.09,
        plate_elongation: 1.8,
        plate_dome: 0.5,
        plate_edge_lift: 0.22,
        plate_identity: 0.55,
        weathering_strength: 0.5,
        weathering_red: 0.055,
        weathering_green: 0.05,
        weathering_blue: 0.042,
        orientation_strength: 0.4,
        orientation_red: -0.022,
        orientation_green: 0.024,
        orientation_blue: -0.016,
        directional_occlusion: 0.55,
        depth_strength: 0.6,
    }
}

pub(super) fn spruce() -> MaterialParams {
    MaterialParams {
        bark_red: 0.147,
        bark_green: 0.078,
        bark_blue: 0.045,
        bark_roughness: 0.9,
        leaf_front_red: 0.018,
        leaf_front_green: 0.056,
        leaf_front_blue: 0.028,
        leaf_back_red: 0.109,
        leaf_back_green: 0.195,
        leaf_back_blue: 0.138,
        hue_range_low: -0.02,
        hue_range_high: 0.02,
        brightness_range_low: -0.10,
        brightness_range_high: 0.10,
        interior_darkening: 0.7,
        ridge_scale: 0.02,
        plate_scale: 0.03,
        furrow_strength: 0.025,
        roughness_detail: 0.16,
        vein_scale: 8.0,
        vein_contrast: 0.0,
        transmission_strength: 0.01,
        transmission_red: 0.12,
        transmission_green: 0.24,
        transmission_blue: 0.08,
        thickness: 3.5,
        fissure_red: -0.035,
        fissure_green: -0.03,
        fissure_blue: -0.02,
        fissure_strength: 0.4,
        crest_red: 0.05,
        crest_green: 0.025,
        crest_blue: 0.01,
        crest_strength: 0.3,
        bark_mottle_scale: 0.4,
        bark_mottle_strength: 0.2,
        cavity_strength: 0.6,
        blade_mottle_scale: 8.0,
        blade_mottle_strength: 0.0,
        margin_width: 0.0,
        margin_red: 0.01,
        margin_green: 0.015,
        margin_blue: 0.002,
        cuticle_gloss: 0.05,
        sky_occlusion_strength: 0.6,
        plate_cell_scale: 0.022,
        plate_elongation: 0.2,
        plate_dome: 0.35,
        plate_edge_lift: 0.7,
        plate_identity: 0.6,
        weathering_strength: 0.4,
        weathering_red: 0.035,
        weathering_green: 0.025,
        weathering_blue: 0.016,
        orientation_strength: 0.45,
        orientation_red: -0.014,
        orientation_green: 0.026,
        orientation_blue: -0.008,
        directional_occlusion: 0.45,
        depth_strength: 0.45,
    }
}

pub(super) fn radiant(silver: bool) -> MaterialParams {
    MaterialParams {
        fissure_strength: 0.12,
        crest_strength: 0.1,
        bark_mottle_strength: 0.05,
        blade_mottle_strength: 0.04,
        cavity_strength: 0.2,
        cuticle_gloss: if silver { 0.25 } else { 0.3 },
        sky_occlusion_strength: 0.2,
        ..MaterialParams::default()
    }
}
