//! Material value tables kept beside the geometry presets.
use crate::material::MaterialParams;

pub(super) fn oak() -> MaterialParams {
    MaterialParams {
        bark_red: 0.225,
        bark_green: 0.218,
        bark_blue: 0.198,
        bark_roughness: 0.85,
        // Neutral: no young wood until the oak's own table states it.
        shoot_red: 0.225,
        shoot_green: 0.218,
        shoot_blue: 0.198,
        shoot_radius: 0.0,
        leaf_front_red: 0.028,
        leaf_front_green: 0.102,
        leaf_front_blue: 0.016,
        leaf_back_red: 0.153,
        leaf_back_green: 0.254,
        leaf_back_blue: 0.112,
        hue_range_low: -0.03,
        hue_range_high: 0.03,
        brightness_range_low: -0.15,
        brightness_range_high: 0.15,
        interior_darkening: 0.55,
        ridge_scale: 0.032,
        plate_scale: 0.055,
        furrow_strength: 1.0,
        roughness_detail: 0.12,
        vein_scale: 7.0,
        vein_contrast: 0.45,
        transmission_strength: 0.55,
        transmission_red: 0.24,
        transmission_green: 0.52,
        transmission_blue: 0.07,
        thickness: 0.65,
        fissure_red: -0.1,
        fissure_green: -0.05,
        fissure_blue: 0.005,
        fissure_strength: 0.65,
        crest_red: 0.1,
        crest_green: 0.085,
        crest_blue: 0.055,
        crest_strength: 0.5,
        bark_mottle_scale: 0.8,
        bark_mottle_strength: 0.2,
        cavity_strength: 0.6,
        blade_mottle_scale: 6.0,
        blade_mottle_strength: 0.15,
        margin_width: 0.08,
        margin_red: 0.025,
        margin_green: 0.035,
        margin_blue: 0.006,
        cuticle_gloss: 0.35,
        sky_occlusion_strength: 0.5,
    }
}

pub(super) fn spruce() -> MaterialParams {
    MaterialParams {
        bark_red: 0.147,
        bark_green: 0.078,
        bark_blue: 0.045,
        bark_roughness: 0.9,
        // Neutral: no young wood until the spruce's own table states it.
        shoot_red: 0.147,
        shoot_green: 0.078,
        shoot_blue: 0.045,
        shoot_radius: 0.0,
        leaf_front_red: 0.018,
        leaf_front_green: 0.056,
        leaf_front_blue: 0.028,
        leaf_back_red: 0.109,
        leaf_back_green: 0.195,
        leaf_back_blue: 0.138,
        hue_range_low: -0.02,
        hue_range_high: 0.02,
        brightness_range_low: -0.10,
        brightness_range_high: 0.10,
        interior_darkening: 0.7,
        ridge_scale: 0.02,
        plate_scale: 0.03,
        furrow_strength: 0.025,
        roughness_detail: 0.16,
        vein_scale: 8.0,
        vein_contrast: 0.0,
        transmission_strength: 0.01,
        transmission_red: 0.12,
        transmission_green: 0.24,
        transmission_blue: 0.08,
        thickness: 3.5,
        fissure_red: -0.035,
        fissure_green: -0.03,
        fissure_blue: -0.02,
        fissure_strength: 0.4,
        crest_red: 0.05,
        crest_green: 0.025,
        crest_blue: 0.01,
        crest_strength: 0.3,
        bark_mottle_scale: 0.4,
        bark_mottle_strength: 0.2,
        cavity_strength: 0.6,
        blade_mottle_scale: 8.0,
        blade_mottle_strength: 0.0,
        margin_width: 0.0,
        margin_red: 0.01,
        margin_green: 0.015,
        margin_blue: 0.002,
        cuticle_gloss: 0.05,
        sky_occlusion_strength: 0.6,
    }
}

pub(super) fn beech() -> MaterialParams {
    MaterialParams {
        bark_red: 0.36,
        bark_green: 0.335,
        bark_blue: 0.295,
        bark_roughness: 0.4,
        // Young shoots light olive- to grey-brown (VT Dendrology, Fagus
        // sylvatica: "slender, zigzag, light brown"; OSU: stems olive-brown),
        // grey by the second or third year. B-BARE's winter crown haze reads
        // linear 0.064/0.055/0.033 to 0.149/0.136/0.097 on its own exposure,
        // R:G:B 1:0.86:0.52 in its darker band. The birch's matched still
        // drew a row redder by 0.85 in green and 0.78 in blue, so the row is
        // set greener than the band; unrendered until the beech's table lands.
        // Smooth grey from about 1.6 cm across.
        shoot_red: 0.14,
        shoot_green: 0.13,
        shoot_blue: 0.085,
        shoot_radius: 0.004,
        leaf_front_red: 0.022,
        leaf_front_green: 0.105,
        leaf_front_blue: 0.018,
        leaf_back_red: 0.14,
        leaf_back_green: 0.23,
        leaf_back_blue: 0.1,
        hue_range_low: -0.02,
        hue_range_high: 0.02,
        brightness_range_low: -0.1,
        brightness_range_high: 0.1,
        interior_darkening: 0.35,
        ridge_scale: 0.018,
        plate_scale: 0.04,
        furrow_strength: 0.12,
        roughness_detail: 0.08,
        vein_scale: 7.0,
        vein_contrast: 0.4,
        transmission_strength: 0.5,
        transmission_red: 0.22,
        transmission_green: 0.5,
        transmission_blue: 0.08,
        thickness: 0.6,
        fissure_red: -0.04,
        fissure_green: -0.03,
        fissure_blue: -0.02,
        fissure_strength: 0.2,
        crest_red: 0.06,
        crest_green: 0.055,
        crest_blue: 0.045,
        crest_strength: 0.25,
        bark_mottle_scale: 0.6,
        bark_mottle_strength: 0.12,
        cavity_strength: 0.35,
        blade_mottle_scale: 5.0,
        blade_mottle_strength: 0.1,
        margin_width: 0.04,
        margin_red: 0.02,
        margin_green: 0.04,
        margin_blue: 0.008,
        cuticle_gloss: 0.48,
        sky_occlusion_strength: 0.35,
    }
}

pub(super) fn birch() -> MaterialParams {
    MaterialParams {
        bark_red: 0.78,
        bark_green: 0.76,
        bark_blue: 0.7,
        bark_roughness: 0.48,
        // Young shoots dark red-brown, glossy, with pale resin warts; the
        // bark whitens only once it has thickened (VT Dendrology, Betula
        // pendula: twigs "slender, reddish brown"; bark "reddish brown ...
        // when very young, later turning white"; Atkinson 1992). S-BARE's
        // winter crown haze reads linear 0.061/0.042/0.030 to 0.149/0.093/
        // 0.066 on the exposure its trunk reads 0.78/0.78/0.71 on, R:G:B
        // 1:0.69:0.49 in its darker band. The matched still reddens a row:
        // 0.10/0.06/0.045 drew that band at 1:0.51:0.35, so the row is the
        // greyer red-brown that draws it near the photograph's. White from
        // about 4 cm across.
        shoot_red: 0.095,
        shoot_green: 0.07,
        shoot_blue: 0.055,
        shoot_radius: 0.01,
        leaf_front_red: 0.055,
        leaf_front_green: 0.165,
        leaf_front_blue: 0.035,
        leaf_back_red: 0.18,
        leaf_back_green: 0.27,
        leaf_back_blue: 0.11,
        hue_range_low: -0.025,
        hue_range_high: 0.025,
        brightness_range_low: -0.12,
        brightness_range_high: 0.12,
        interior_darkening: 0.4,
        ridge_scale: 0.025,
        plate_scale: 0.05,
        furrow_strength: 0.25,
        roughness_detail: 0.1,
        vein_scale: 6.0,
        vein_contrast: 0.35,
        transmission_strength: 0.6,
        transmission_red: 0.28,
        transmission_green: 0.55,
        transmission_blue: 0.1,
        thickness: 0.45,
        fissure_red: -0.25,
        fissure_green: -0.24,
        fissure_blue: -0.22,
        fissure_strength: 0.45,
        crest_red: 0.08,
        crest_green: 0.07,
        crest_blue: 0.06,
        crest_strength: 0.2,
        bark_mottle_scale: 0.9,
        bark_mottle_strength: 0.18,
        cavity_strength: 0.3,
        blade_mottle_scale: 5.5,
        blade_mottle_strength: 0.12,
        margin_width: 0.05,
        margin_red: 0.03,
        margin_green: 0.05,
        margin_blue: 0.01,
        cuticle_gloss: 0.28,
        sky_occlusion_strength: 0.4,
    }
}

pub(super) fn radiant(silver: bool) -> MaterialParams {
    MaterialParams {
        fissure_strength: 0.12,
        crest_strength: 0.1,
        bark_mottle_strength: 0.05,
        blade_mottle_strength: 0.04,
        cavity_strength: 0.2,
        cuticle_gloss: if silver { 0.25 } else { 0.3 },
        sky_occlusion_strength: 0.2,
        ..MaterialParams::default()
    }
}
