import { execFileSync } from 'node:child_process';
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown', '-p', 'telperion-wasm'], { cwd: root, stdio: 'inherit', timeout: 600_000 });
const source = new URL('target/wasm32-unknown-unknown/release/telperion_wasm.wasm', root);
const { instance } = await WebAssembly.instantiate(await readFile(source), { env: { now: () => performance.now() } });
const e = instance.exports;
const presets = [0, 1, 2].map(id => {
  if (e.preset(id)) throw Error('Rust preset metadata failed');
  return JSON.parse(new TextDecoder().decode(new Uint8Array(e.memory.buffer, e.metadata_ptr(), e.metadata_len())));
});
function type(v) {
  return typeof v === 'object' && v !== null ? '{\n' + Object.entries(v).map(([k, x]) => `  ${k}${x === null ? '?' : ''}: ${x === null ? 'number' : type(x)};`).join('\n') + '\n}' : typeof v;
}
function stripNull(v) {
  if (typeof v !== 'object' || v === null) return v;
  return Object.fromEntries(Object.entries(v).filter(([, x]) => x !== null).map(([k, x]) => [k, stripNull(x)]));
}
const generated = new URL('src/browser/presets.generated.ts', root);
const content = '// Generated by scripts/build-wasm.mjs from Rust presets. Do not edit.\n' +
  `export interface Family ${type(presets[0])}\n` +
  `export const FAMILIES: Family[] = ${JSON.stringify(presets.map(stripNull), null, 2)};\n`;
await mkdir(new URL('src/browser/', root), { recursive: true });
await writeFile(generated, content);
await copyFile(source, new URL('src/browser/telperion.wasm', root));
console.log('Built Wasm and regenerated Rust family metadata.');
