import { execFileSync } from 'node:child_process';
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown', '-p', 'telperion-wasm'], { cwd: root, stdio: 'inherit', timeout: 600_000 });
const source = new URL('target/wasm32-unknown-unknown/release/telperion_wasm.wasm', root);
const { instance } = await WebAssembly.instantiate(await readFile(source), { env: { now: () => performance.now() } });
const e = instance.exports;
if (e.catalogue()) throw Error('Rust catalogue metadata failed');
const catalogue = JSON.parse(new TextDecoder().decode(new Uint8Array(e.memory.buffer, e.metadata_ptr(), e.metadata_len())));
function stripNull(v) {
  if (typeof v !== 'object' || v === null) return v;
  return Object.fromEntries(Object.entries(v).filter(([, x]) => x !== null).map(([k, x]) => [k, stripNull(x)]));
}
const generated = new URL('src/browser/presets.generated.ts', root);
// The family's type is the catalogue's (parameters.generated.ts); only the
// preset values are read out of the binding here.
const content = '// Generated by scripts/build-wasm.mjs from Rust presets. Do not edit.\n' +
  'import type { Family } from "./parameters.generated";\n' +
  'export type { Family };\n' +
  `export const CATALOGUE: { abiId: number; id: string; name: string; note: string; family: Family }[] = ${JSON.stringify(catalogue.map(stripNull), null, 2)};\n`;
await mkdir(new URL('src/browser/', root), { recursive: true });
await writeFile(generated, content);
// Each binding sits beside its entry point, in the source for the dev server
// and in dist for the package, so `new URL(..., import.meta.url)` finds it at
// run time and a Node caller reads it from the same place. Nothing is inlined
// into the scripts.
await mkdir(new URL('dist/', root), { recursive: true });
await copyFile(source, new URL('src/browser/telperion.wasm', root));
await copyFile(source, new URL('dist/telperion.wasm', root));
// The slim binding (crates/telperion-field): the core without its geometry, no JSON.
// Its function names are stripped here, for the package only: the download is
// the point of the slim entry, and test binaries keep their symbols.
const strip = ['--config', 'profile.release.package.telperion-field.strip=true'];
execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown', '-p', 'telperion-field', ...strip], { cwd: root, stdio: 'inherit', timeout: 600_000 });
const slim = new URL('target/wasm32-unknown-unknown/release/telperion_field.wasm', root);
await copyFile(slim, new URL('src/field/telperion-field.wasm', root));
await copyFile(slim, new URL('dist/telperion-field.wasm', root));
console.log('Built the full and the slim Wasm and regenerated Rust family metadata.');
