import { execFileSync } from 'node:child_process';
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
execFileSync('cargo', ['build', '--release', '--target', 'wasm32-unknown-unknown', '-p', 'telperion-wasm'], { cwd: root, stdio: 'inherit', timeout: 600_000 });
const source = new URL('target/wasm32-unknown-unknown/release/telperion_wasm.wasm', root);
const { instance } = await WebAssembly.instantiate(await readFile(source), { env: { now: () => performance.now() } });
const e = instance.exports;
if (e.catalogue()) throw Error('Rust catalogue metadata failed');
const catalogue = JSON.parse(new TextDecoder().decode(new Uint8Array(e.memory.buffer, e.metadata_ptr(), e.metadata_len())));
const presets = catalogue.map(entry => entry.family);
function type(values) {
  const present = values.filter(v => v !== null);
  if (!present.length) return 'number';
  if (typeof present[0] === 'string') return [...new Set(present)].map(v => JSON.stringify(v)).join(' | ');
  if (typeof present[0] !== 'object') return typeof present[0];
  // Tagged variants retain their exact fields; all shapes come from native presets.
  if ('kind' in present[0]) return [...new Set(present.map(v => typeObject([v])))].join(' | ');
  return typeObject(present);
}
function typeObject(values) {
  const keys = [...new Set(values.flatMap(v => Object.keys(v)))];
  return '{\n' + keys.map(k => {
    const members = values.map(v => v[k]);
    return `  ${k}${members.some(v => v == null) ? '?' : ''}: ${type(members.filter(v => v !== undefined))};`;
  }).join('\n') + '\n}';
}
function stripNull(v) {
  if (typeof v !== 'object' || v === null) return v;
  return Object.fromEntries(Object.entries(v).filter(([, x]) => x !== null).map(([k, x]) => [k, stripNull(x)]));
}
const generated = new URL('src/browser/presets.generated.ts', root);
const content = '// Generated by scripts/build-wasm.mjs from Rust presets. Do not edit.\n' +
  `export interface Family ${type(presets)}\n` +
  `export const CATALOGUE: { abiId: number; id: string; name: string; note: string; family: Family }[] = ${JSON.stringify(catalogue.map(stripNull), null, 2)};\n`;
await mkdir(new URL('src/browser/', root), { recursive: true });
await writeFile(generated, content);
await copyFile(source, new URL('src/browser/telperion.wasm', root));
console.log('Built Wasm and regenerated Rust family metadata.');
