#!/usr/bin/env node
// Renders the browsable view of the catalogue: one page per species and one
// index. The records are the truth and a page is a view of them, so nothing
// here is ever authored by hand - `catalogue-check.mjs` fails a page whose
// committed bytes differ from what this file regenerates.
//
//   node scripts/catalogue-pages.mjs
//
// Takes no arguments and is idempotent. GitHub renders the written markdown as
// the folder's page with LFS images inline, and Obsidian opens `catalogue/` as
// a vault; neither needs a server.
import { readFileSync, readdirSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const CATALOGUE = 'catalogue';

const json = (root, path) => JSON.parse(readFileSync(join(root, path), 'utf8'));
const isEmpty = (record) => record?.empty === true;

/** Every species id in the catalogue, sorted. */
export function speciesIds(root = ROOT) {
  const dir = join(root, CATALOGUE);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((name) => statSync(join(dir, name)).isDirectory())
    .sort();
}

/** Every record of one species, read off disk. */
export function readSpecies(root, id) {
  const at = (name) => json(root, join(CATALOGUE, id, name));
  return {
    id,
    sources: at('sources.json'),
    manifest: at('manifest.json'),
    profile: at('packet/profile.json'),
    references: at('packet/references.json'),
    species: at('packet/species.json'),
    specimens: at('packet/specimens.json'),
    pins: at('pins.json'),
    stills: at('stills.json'),
    notes: readFileSync(join(root, CATALOGUE, id, 'NOTES.md'), 'utf8'),
  };
}

const escape = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();

function table(headers, rows) {
  if (rows.length === 0) return '_None recorded._\n';
  const lines = [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`];
  for (const row of rows) lines.push(`| ${row.map(escape).join(' | ')} |`);
  return `${lines.join('\n')}\n`;
}

/** The verdict a species' stills carry, as one word for the index. */
export function verdictOf(stills) {
  const rows = stills.stills ?? [];
  if (rows.length === 0) return 'no stills';
  const statuses = new Set(rows.map((row) => row.visual_status ?? 'unassessed'));
  if (statuses.has('fail')) return 'fail';
  if (statuses.size === 1 && statuses.has('pass')) return 'pass';
  if (statuses.has('pass')) return 'part-assessed';
  return 'unassessed';
}

/** The Hallé and Oldeman model, once a species record names one. */
const modelOf = (record) => record.species.architectural_model ?? 'not recorded';

function speciesPage(species) {
  const profile = species.profile.profiles?.[0] ?? {};
  const record = species.species;
  const out = [];

  out.push(`# ${profile.common_name ?? record.common_name ?? species.id}\n`);
  out.push('<!-- Generated by scripts/catalogue-pages.mjs. Do not edit; write in NOTES.md. -->\n');
  out.push(table(
    ['Field', 'Value'],
    [
      ['Catalogue id', species.id],
      ['Scientific name', record.scientific_name],
      ['Rank', record.taxon_rank],
      ['Cultivar', record.cultivar ?? 'none'],
      ['Context', record.context],
      ['Architectural model', modelOf(species)],
      ['Preset', record.preset ?? 'none yet'],
      ['Profile readiness', profile.readiness ?? 'unknown'],
    ],
  ));

  out.push('\n## Bibliography\n');
  out.push(table(
    ['Id', 'Source', 'Rights', 'Verified', 'Good for'],
    (species.sources.sources ?? []).map((source) => [
      source.id,
      `[${source.title}](${source.url})`,
      source.rights,
      source.verified ?? 'unverified',
      source.use ?? '',
    ]),
  ));

  out.push('\n## Identity pins\n');
  if (isEmpty(species.pins)) {
    out.push('_No preset ships for this species yet, so there is nothing to pin._\n');
  } else {
    const pins = species.pins.pins;
    out.push(table(
      ['Pin', 'Value'],
      [
        ['Seed', species.pins.seed],
        ['Wood vertices', pins.wood_vertices],
        ['Wood triangles', pins.wood_triangles],
        ['Leaf instances', pins.instances],
        ['Bounds min', pins.min.join(', ')],
        ['Bounds max', pins.max.join(', ')],
        ['Skeleton hash', pins.skeleton],
        ['Placement hash', pins.placement],
        ['Element hash', pins.element],
        ['Leaf band', species.pins.leaf_band.join(' to ')],
        ['Growth reference', `${species.pins.growth_reference.height_m} m at ${species.pins.growth_reference.age} years`],
      ],
    ));
  }

  const references = species.references.references ?? [];
  const kept = references.filter((reference) => reference.kept === true);
  out.push('\n## Reference images\n');
  out.push(table(
    ['Id', 'Scale', 'Kept', 'Source', 'Observation'],
    references.map((reference) => [
      reference.id,
      (reference.scale ?? []).join(', '),
      reference.kept ? `\`${reference.path}\`` : 'by url only',
      reference.source_id,
      reference.observation ?? '',
    ]),
  ));
  for (const reference of kept) {
    out.push(`\n![${escape(reference.id)}](${reference.path})\n`);
    out.push(`\n_${escape(reference.attribution)}_\n`);
  }

  out.push('\n## Stills\n');
  out.push(table(
    ['Still', 'Preset', 'Seed', 'View', 'Verdict', 'Owner'],
    (species.stills.stills ?? []).map((still) => [
      `\`${still.path}\``,
      still.preset,
      still.seed,
      still.view,
      still.visual_status ?? 'unassessed',
      still.owner_feedback ?? '',
    ]),
  ));

  out.push('\n## Pipeline\n');
  out.push(isEmpty(species.manifest)
    ? '_This species predates the pipeline; no manifest has been admitted._\n'
    : table(
      ['Field', 'Value'],
      [
        ['Growth form', species.manifest.growth_form],
        ['Seed', species.manifest.seed],
        ['Model', species.manifest.model],
        ['Admitted sources', (species.manifest.sources ?? []).map((source) => source.id).join(', ')],
      ],
    ));

  out.push('\n## Notes\n\n');
  out.push(species.notes.endsWith('\n') ? species.notes : `${species.notes}\n`);
  return out.join('');
}

function indexPage(all) {
  const out = [];
  out.push('# The species catalogue\n');
  out.push('<!-- Generated by scripts/catalogue-pages.mjs. Do not edit; write in a species NOTES.md. -->\n');
  out.push('\nOne folder per species, and the folder is the only place that species\' record lives:\n');
  out.push('its bibliography, its admitted manifest, its packet, the pins the tests read, the\n');
  out.push('reference images the project may keep, and the owner\'s notes. A run under\n');
  out.push('`.flow/evidence/` refers to a species by its catalogue id and copies nothing out.\n');
  out.push('\n');
  out.push(table(
    ['Species', 'Scientific name', 'Architectural model', 'Preset', 'Sources', 'Verdict'],
    all.map((species) => [
      `[${species.profile.profiles?.[0]?.common_name ?? species.id}](${species.id}/README.md)`,
      species.species.scientific_name,
      modelOf(species),
      species.species.preset ?? 'none yet',
      (species.sources.sources ?? []).length,
      verdictOf(species.stills),
    ]),
  ));
  return out.join('');
}

/** Every page the catalogue should carry, as repo-relative path to content. */
export function renderPages(root = ROOT) {
  const all = speciesIds(root).map((id) => readSpecies(root, id));
  const pages = new Map();
  for (const species of all) {
    pages.set(join(CATALOGUE, species.id, 'README.md'), speciesPage(species));
  }
  if (all.length > 0) pages.set(join(CATALOGUE, 'README.md'), indexPage(all));
  return pages;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const pages = renderPages();
  for (const [path, content] of pages) writeFileSync(join(ROOT, path), content);
  console.log(`catalogue: wrote ${pages.size} page${pages.size === 1 ? '' : 's'}`);
}
