#!/usr/bin/env node
// The species article: the sources distilled into an encyclopedia entry, with
// a citation on every claim.
//
//   node scripts/catalogue-article.mjs --species <id>
//
// The command assembles the record material and the source copies, scaffolds
// `catalogue/<id>/ARTICLE.md` when there is none, refreshes every generated
// block when there is, and records the sha256 of each record and source copy
// the article was written from. A written article cannot be regenerated byte
// for byte, so `catalogue-check.mjs` gates it on those checksums instead: when
// an input moves the article is rewritten, not patched.
//
// The division of labour is the project's standing rule. Code owns every
// number: the measurement table is rendered from `packet/profile.json` with
// each range, unit, confidence and note as the record holds them. The writer
// owns selection, order and phrasing, one sentence per line, each line ending
// in the source it rests on. A number in authored prose that appears in no
// packet record, and a prose line with no citation, both fail the check.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROOT, CATALOGUE, readSpecies } from './catalogue-pages.mjs';
import { readFrontMatter, writeFrontMatter, sourceCopyPath } from './catalogue-sources.mjs';

/** The entry's shape, fixed so every species reads the same way. */
export const SECTIONS = [
  ['Identity', 'What the tree is, where it grows and how the record frames it.'],
  ['Size and growth', 'How large it grows and by what age.'],
  ['Crown and habit', 'The silhouette, the branching and how the crown fills.'],
  ['Bark', 'What the bark looks like and how it changes with age.'],
  ['Leaves', 'The blade, its attachment and its arrangement.'],
  ['What the record does not know', 'The gaps this catalogue has not closed.'],
];

const PACKET = ['packet/profile.json', 'packet/references.json', 'packet/species.json', 'packet/specimens.json'];
const BLOCK = /<!-- generated: ([a-z]+) -->[\s\S]*?<!-- \/generated -->/g;
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const escape = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

const block = (name, content) => `<!-- generated: ${name} -->\n${content}<!-- /generated -->`;

function table(headers, rows) {
  const lines = [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`];
  for (const row of rows) lines.push(`| ${row.map(escape).join(' | ')} |`);
  return `${lines.join('\n')}\n`;
}

/** Every number the packet records, as the strings a reader would write. */
export function packetNumbers(root, id) {
  const found = new Set();
  for (const file of PACKET) {
    const text = readFileSync(join(root, CATALOGUE, id, file), 'utf8');
    for (const token of text.match(/\d+(?:\.\d+)?/g) ?? []) {
      found.add(token);
      // 0.025 in the record is 2.5 cm in a note and 25 mm in a source; a
      // trailing zero is the same measurement written differently.
      if (token.includes('.')) found.add(token.replace(/0+$/, '').replace(/\.$/, ''));
    }
  }
  return found;
}

/** The measurement table, rendered from the record and never from the writer. */
function measurements(species) {
  const profile = species.profile.profiles?.[0] ?? {};
  const rows = Object.entries(profile.metrics ?? {})
    .filter(([, metric]) => Array.isArray(metric.range))
    .map(([name, metric]) => [
      name,
      metric.range.join(' to '),
      metric.unit,
      `${metric.classification}, ${metric.confidence}`,
      (metric.source ?? []).join(', ') || 'none cited',
      metric.note,
    ]);
  if (rows.length === 0) return '_The record holds no measured range for this species._\n';
  return table(['Measurement', 'Range', 'Unit', 'Standing', 'Sources', 'Note'], rows);
}

function header(species) {
  const profile = species.profile.profiles?.[0] ?? {};
  const record = species.species;
  return [
    `# ${profile.common_name ?? species.id}`,
    '',
    `_${record.scientific_name}_ — ${record.context}`,
    '',
    'Distilled from the sources copied into this folder. Every claim carries the source it rests on;',
    'every measurement is copied by code from the packet with the record\'s own standing beside it.',
    '',
  ].join('\n');
}

function bibliography(species) {
  const rows = (species.sources.sources ?? []).map((source) => [
    source.id,
    `[${source.title}](${source.url})`,
    `[copy](sources/${source.id}.md)`,
    source.rights,
  ]);
  return `## Sources\n\n${table(['Id', 'Original', 'Local copy', 'Rights'], rows)}`;
}

const BLOCKS = {
  header,
  measurements,
  sources: bibliography,
};

const generated = (name, species) => block(name, `${BLOCKS[name](species).trimEnd()}\n`);

function scaffold(species) {
  const parts = [generated('header', species)];
  for (const [name, hint] of SECTIONS) {
    parts.push(`## ${name}\n\nTODO: ${hint}`);
    if (name === 'Size and growth') parts.push(generated('measurements', species));
  }
  parts.push(generated('sources', species));
  return `${parts.join('\n\n')}\n`;
}

/** Lines the writer authored: outside every generated block and every heading. */
export function authoredLines(body) {
  const lines = body.split('\n');
  const out = [];
  let generated = false;
  lines.forEach((line, index) => {
    if (/<!-- generated: [a-z]+ -->/.test(line)) generated = true;
    else if (/<!-- \/generated -->/.test(line)) generated = false;
    else if (!generated && line.trim() !== '' && !line.startsWith('#')) {
      out.push({ line: index + 1, text: line });
    }
  });
  return out;
}

const delink = (text) => text.replace(/\[[^\]]*\]\([^)]*\)/g, ' ');
const CITATION = /\[([A-Z0-9][A-Z0-9-]*)\]\(sources\/([A-Z0-9][A-Z0-9-]*)\.md\)/g;

/**
 * Every failure an article carries, in the check's `<path>: <reason>` voice.
 * Claims, numbers, sections and the source copies the article needs.
 */
export function validateArticle(root, id, species) {
  const where = `${CATALOGUE}/${id}/ARTICLE.md`;
  const failures = [];
  const path = join(root, CATALOGUE, id, 'ARTICLE.md');
  if (!existsSync(path)) return [`${CATALOGUE}/${id}: missing ARTICLE.md`];

  const { front, body } = readFrontMatter(readFileSync(path, 'utf8'));
  if (!front) return [`${where}: has no front matter`];

  const sourceIds = new Set((species.sources.sources ?? []).map((source) => source.id));
  for (const name of Object.keys(BLOCKS)) {
    if (!new RegExp(`<!-- generated: ${name} -->`).test(body)) {
      failures.push(`${where}: generated block ${name} is missing`);
    }
  }
  for (const [name] of SECTIONS) {
    const section = new RegExp(`^## ${name}\\s*$([\\s\\S]*?)(?=^## |\\Z)`, 'm').exec(body);
    if (!section) failures.push(`${where}: section "${name}" is missing`);
    else if (authoredLines(section[1]).length === 0) failures.push(`${where}: section "${name}" is unfilled`);
  }

  const numbers = packetNumbers(root, id);
  for (const { line, text } of authoredLines(body)) {
    if (/\bTODO\b/.test(text)) {
      failures.push(`${where}:${line}: is still a TODO`);
      continue;
    }
    const cited = [...text.matchAll(CITATION)];
    if (cited.length === 0) failures.push(`${where}:${line}: claim carries no source id`);
    for (const [, label, target] of cited) {
      if (label !== target) failures.push(`${where}:${line}: citation ${label} does not link to its own copy`);
      else if (!sourceIds.has(label)) failures.push(`${where}:${line}: cites ${label}, which is in no sources.json record`);
    }
    for (const token of delink(text).match(/\d+(?:\.\d+)?/g) ?? []) {
      if (!numbers.has(token)) failures.push(`${where}:${line}: the number ${token} appears in no packet record`);
    }
  }

  for (const source of species.sources.sources ?? []) {
    if (!existsSync(sourceCopyPath(root, id, source.id))) {
      failures.push(`${CATALOGUE}/${id}/sources/${source.id}.md: missing, so the article cannot cite it`);
    }
  }
  return failures;
}

/** The record and source-copy checksums an article is written from. */
export function articleInputs(root, id, species) {
  const inputs = {};
  for (const file of [...PACKET, 'sources.json']) {
    inputs[file] = sha256(readFileSync(join(root, CATALOGUE, id, file)));
  }
  for (const source of species.sources.sources ?? []) {
    const path = sourceCopyPath(root, id, source.id);
    if (existsSync(path)) inputs[`sources/${source.id}.md`] = sha256(readFileSync(path));
  }
  return inputs;
}

/** Every input an article recorded that has since moved. */
export function staleInputs(root, id) {
  const path = join(root, CATALOGUE, id, 'ARTICLE.md');
  const { front } = readFrontMatter(readFileSync(path, 'utf8'));
  const recorded = front?.inputs ?? {};
  const moved = [];
  for (const [file, digest] of Object.entries(recorded)) {
    const at = join(root, CATALOGUE, id, file);
    if (!existsSync(at)) moved.push(file);
    else if (sha256(readFileSync(at)) !== digest) moved.push(file);
  }
  return moved;
}

/** Write the article: scaffold it, or refresh its generated blocks and inputs. */
export function writeArticle(root, id) {
  const species = readSpecies(root, id);
  const path = join(root, CATALOGUE, id, 'ARTICLE.md');
  const missing = (species.sources.sources ?? [])
    .filter((source) => !existsSync(sourceCopyPath(root, id, source.id)));
  if (missing.length > 0) {
    return { path, wrote: false, failures: missing.map((source) =>
      `${CATALOGUE}/${id}/sources/${source.id}.md: missing, so the article cannot be written`) };
  }

  const existing = existsSync(path) ? readFrontMatter(readFileSync(path, 'utf8')).body : null;
  const body = (existing ?? scaffold(species))
    .replace(BLOCK, (whole, name) => (BLOCKS[name] ? generated(name, species) : whole))
    .replace(/^\n+/, '');

  const front = writeFrontMatter({
    species: id,
    written: new Date().toISOString().slice(0, 10),
    sources: (species.sources.sources ?? []).map((source) => source.id),
    inputs: articleInputs(root, id, species),
  });
  writeFileSync(path, `${front}\n${body.replace(/\n*$/, '\n')}`);
  return { path, wrote: true, scaffolded: existing === null, failures: validateArticle(root, id, species) };
}

function main() {
  const at = process.argv.indexOf('--species');
  const species = at === -1 ? null : process.argv[at + 1];
  if (!species) {
    console.error('usage: node scripts/catalogue-article.mjs --species <id>');
    process.exit(2);
  }
  const result = writeArticle(ROOT, species);
  if (!result.wrote) {
    for (const failure of result.failures) console.error(failure);
    process.exit(1);
  }
  console.log(`${result.scaffolded ? 'scaffolded' : 'refreshed'} ${CATALOGUE}/${species}/ARTICLE.md`);
  if (result.failures.length > 0) {
    for (const failure of result.failures) console.error(failure);
    console.error(`\n${species}: ${result.failures.length} failure${result.failures.length === 1 ? '' : 's'} left for the writer`);
    process.exit(1);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
